version: "3.1"

services:
  db:
    image: mysql:latest
    ports:
      - 1001:3306
    environment:
      - MYSQL_USER=lvault
      - MYSQL_PASSWORD=lvault_pass
      - MYSQL_DATABASE=lvault_db
      - MYSQL_ROOT_PASSWORD=lvault_root_pass
    command: 
      - --skip-log-bin

  console:
    image: adminer:latest
    ports:
      - 1002:8080

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 1003:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev